[project]
name = "facility-service-requests"
version = "0.1.0"
description = ""
authors = [
    {name = "Rodion",email = "eyattack@gmail.com"}
]
requires-python = ">=3.13, <3.14"
dependencies = [
    "fastapi (>=0.141.1,<0.142.0)",
    "uvicorn (>=0.52.1,<0.53.0)",
    "asyncpg (>=0.31.0,<0.32.0)",
    "pydantic (>=2.13.4,<3.0.0)",
    "pydantic-settings (>=2.15.0,<3.0.0)",
    "uuid-utils (>=0.17.0,<0.18.0)",
    "datetime (>=6.0,<7.0)"
]

[tool.poetry]
packages = [{include = "app"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-asyncio (>=1.4.0,<2.0.0)",
    "alembic (>=1.19.1,<2.0.0)",
    "ruff (>=0.16.2,<0.17.0)",
    "mypy (>=2.3.0,<3.0.0)"
]

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "I",    # isort (сортировка импортов)
    "UP",   # pyupgrade
    "B",    # flake8-bugbear (частые баги)
    "ASYNC", # проверки на async-код — полезно именно для твоего проекта
]
ignore = []

[tool.ruff.format]
quote-style = "double"

[tool.mypy]
python_version = "3.13"
strict = true
plugins = ["pydantic.mypy"]
warn_unused_ignores = true
warn_return_any = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false
